# Generated by Django 3.2.7 on 2021-09-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('appearance', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
