# Generated by Django 3.2.7 on 2021-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('released', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=30)),
                ('album_cover', models.FileField(upload_to='album_cover/')),
            ],
        ),
    ]
