# Generated by Django 3.2.7 on 2021-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTS', '0003_auto_20210910_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
