# Generated by Django 3.2.7 on 2021-09-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BTS', '0004_auto_20210910_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('stars', models.CharField(max_length=5)),
                ('album_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BTS.albums')),
            ],
        ),
    ]
